version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html  # your web server directory
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
