version: 0.0
os: linux

files:
  # Copies all files from the root of the project (deployment archive) to /var/www/html
  - source: /  
    destination: /var/www/html

permissions:
  # Set the permissions for directories
  - object: /var/www/html
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory

  # Set the permissions for files
  - object: /var/www/html
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/fix_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
