version: 0.2

phases:
  build:
    commands:
      - echo "Building website files"
      - mkdir -p output
      # Copy all HTML and CSS files to output directory
      - find . -name "*.html" -exec cp --parents {} output \;
      - find . -name "*.css" -exec cp --parents {} output \;
      # Verify files were copied
      - echo "Contents of output directory:"
      - ls -la output/

artifacts:
  files:
    - '**/*'
  base-directory: 'output'
