version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install"
  pre_build:
    commands:
      - echo "Preparing build"
      - mkdir -p dist
  build:
    commands:
      - echo "Build started on $(date)"
      - cp index.html styles.css dist/
      - cp -r scripts dist/
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
