version: 0.2

phases:
  install:
    commands:
      - echo "Checking files..."
      - ls -la
      - echo "Current directory: $(pwd)"
  
  build:
    commands:
      - echo "Copying files to artifact directory"
      - mkdir -p artifact
      - cp index.html styles.css artifact/

artifacts:
  files:
    - '**/*'
  base-directory: 'artifact'
