version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - sudo yum update -y || true
  build:
    commands:
      - echo Build started on $(date)
  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - '**/*'
