version: 0.2

phases:
  install:
    commands:
      - echo "Debugging file structure..."
      - pwd
      - ls -la
      - find / -name buildspec.yml 2>/dev/null || echo "File not found anywhere"
  
  build:
    commands:
      - echo "Build phase reached"
