version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Not needed for HTML but often included for potential future needs
  build:
    commands:
      - echo "Building the website"  # For HTML/CSS, this could be empty
      - echo "No actual build needed for static files"
artifacts:
  files:
    - '**/*'  # Include all files
  base-directory: .  # Start from root of repo
